version: 2

registries:
  dirego-github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DIREGO_PACKAGES_TOKEN}}
    scope: "@jagr-dirego"
    replaces-base: false

updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - dirego-github-packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
