version: 2

registries:
  dirego-github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DIREGO_PACKAGES_TOKEN}}
    scope: "@jagr-dirego"
    replaces-base: false

updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - dirego-github-packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: zod
        update-types:
          - version-update:semver-major
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
